JAMNotasBackendBundle:
    resource: "@JazzywebAulasMentorNotasBackendBundle/Resources/config/routing.yml"
    prefix:   /

JAMNotasFrontendBundle:
    resource: "@JazzywebAulasMentorNotasFrontendBundle/Resources/config/routing.yml"
    prefix:   /notas

jamab_alimentos:
    resource: "@JazzywebAulasMentorAlimentosBundle/Resources/config/routing.yml"
    prefix:   /alimentos

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
