# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Jazzyweb\AulasMentor\NotasFrontendBundle\Entity\Usuario: plaintext

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_PREMIUM: [ ROLE_REGISTRADO ]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
             users:
               alberto:  { password: pruebas, roles: [ 'ROLE_REGISTRADO' ] }
               maria: { password: pruebas, roles: [ 'ROLE_PREMIUM' ] }
               miguel: { password: pruebas, roles: [ 'ROLE_ADMIN' ] }

        base_datos:
            entity: { class: JazzywebAulasMentorNotasFrontendBundle:Usuario, property: username }

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # the login page has to be accessible for everybody
        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        # secures part of the application
        demo_secured_area:
            pattern:    ^/demo/secured/
            # it's important to notice that in this case _demo_security_check and _demo_login
            # are route names and that they are specified in the AcmeDemoBundle
            form_login:
                check_path: _demo_security_check
                provider: base_datos
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        jamn_area_publica:
            pattern: ^/notas/(registro|activar|tarifas|contratar|login$)
            security: false
        
        jamn_area_protegida:
            pattern: ^/notas/
            form_login:
                login_path:  /notas/login
                check_path:  /notas/login_check
            logout:
                path:   /notas/logout
                target: /notas

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/notas/miespacio, roles: ROLE_PREMIUM }
        - { path: ^/notas/administracion, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/notas, roles: ROLE_REGISTRADO }