JAMN_ORM_crear:
 pattern:  /estudio_orm/crear
 defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:EstudioORM:crear }
 
JAMN_ORM_recuperar:
 pattern:  /estudio_orm/recuperar/{id}
 defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:EstudioORM:recuperar } 
 
JAMN_ORM_recuperar_notas:
 pattern:  /estudio_orm/recuperar_notas
 defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:EstudioORM:recuperarNotas }
 
JAMN_ORM_DQL:
 pattern:  /estudio_orm/dql
 defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:EstudioORM:dql }
 
jamn_EVF:
 pattern: /estudio_valyforms/valida_usuario
 defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:EstudioValidacionYFormulario:validaUsuario }

jamn_homepage:
     pattern:  /
     defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:Notas:index }
     requirements:
       _method: GET

jamn_conetiqueta:
     pattern:  /conetiqueta/{etiqueta}
     defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:Notas:index }
     requirements:
         id:  \d+
         _method: GET

jamn_buscar:
     pattern:  /buscar
     defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:Notas:index, etiqueta: termino }
     requirements:
       _method: POST

jamn_nota:
     pattern:  /nota/{id}
     defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:Notas:index }
     requirements:
         id:  \d+
         _method: GET

jamn_nueva:
     pattern:  /nueva
     defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:Notas:nueva }

jamn_editar:
     pattern:  /editar/{id}
     defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:Notas:editar }
     requirements:
       id:  \d+

jamn_borrar:
     pattern:  /borrar/{id}
     defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:Notas:borrar }
     requirements:
       id:  \d+

jamn_espacio_premium:
     pattern: /miespacio
     defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:Notas:espacioPremium }

jamn_rss:
     pattern:  /rss
     defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:Notas:rss }
     requirements:
       _method: GET
       _format: xml

jamn_registro:
     pattern:  /registro
     defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:Login:registro }

jamn_activar_cuenta:
     pattern:  /activar/{token}
     defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:Login:activar }

jamn_tarifas:
     pattern:  /tarifas
     defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:Contratos:tarifasPremium }
     requirements:
       _method: GET

jamn_contratar:
     pattern:  /contratar
     defaults: { _controller: JazzywebAulasMentorNotasFrontendBundle:Contratos:contratarPremium }